const fs = require('fs');

const filePath = 'd:/nailform3d be-fe/nailform-project (fe) root/nailform3d/src/pages/AdminDashboard.jsx';

let content = fs.readFileSync(filePath, 'utf-8');

const replacements = {
    'Tổng quan': 'Overview',
    'Duyệt nâng cấp gói': 'Subscription Approvals',
    'Quản lý thành viên': 'Manage Members',
    'Tài nguyên 3D': '3D Assets',
    'Kiểm duyệt Gallery': 'Gallery Moderation',
    'Bảng điều hành Tổng quan': 'Overview Dashboard',
    'Theo dõi các chỉ số tăng trưởng và quản lý mô hình Beauty-Tech SaaS của Nailform 3D.': "Monitor growth metrics and manage Nailform 3D's Beauty-Tech SaaS model.",
    'Doanh thu SaaS \\(ARR\\)': 'SaaS Revenue (ARR)',
    'tháng này': 'this month',
    'Tổng Tiệm Nail B2B': 'Total B2B Salons',
    'tiệm mới': 'new salons',
    'Thiết kế 3D hoạt động': 'Active 3D Designs',
    'bản vẽ': 'designs',
    'tuần qua': 'past week',
    'Khách hàng B2C': 'B2C Customers',
    'đăng ký mới': 'new registrations',
    'Giám sát Cam kết Chiến lược': 'Strategic Commitment Monitoring',
    'Mô hình SaaS tinh khiết: Không thu hoa hồng từ đặt lịch, không giữ tiền cọc \\(Escrow\\), không can thiệp vào giá của tiệm nail.': 'Pure SaaS model: Zero commission from bookings, no escrow, no interference with salon pricing.',
    '0% Phí hoa hồng': '0% Commission',
    '0đ Giữ tiền cọc': '0$ Escrow',
    'Thanh toán trực tiếp': 'Direct Payment',
    'Hoạt động kết nối Marketplace \\(Ước tính gián tiếp\\)': 'Marketplace Connection Activity (Indirect Estimate)',
    'Mặc dù Nailform 3D \\*\\*không thu tiền trung gian\\*\\*, hệ thống vẫn ước tính lượng giao dịch trực tiếp diễn ra giữa khách và tiệm để đánh giá giá trị nền tảng mang lại.': 'Although Nailform 3D **does not collect intermediary fees**, the system still estimates direct transactions between customers and salons to evaluate platform value.',
    'Tổng Giá Trị Lịch Hẹn \\(GMV ước tính\\)': 'Total Booking Value (Est. GMV)',
    'Tổng số lịch hẹn Booking': 'Total Bookings',
    'lượt đặt': 'bookings',
    'Chi phí tiết kiệm cho tiệm \\(0% Com.\\)': 'Cost Savings for Salons (0% Com.)',
    'Phân bố Gói Đăng Ký \\(SaaS Plan Tiers\\)': 'Subscription Plan Distribution',
    'năm': 'year',
    'Phê duyệt nâng cấp Gói đăng ký SaaS': 'SaaS Subscription Approvals',
    'Kiểm duyệt các yêu cầu đăng ký gói VIP của B2C và B2B thông qua hóa đơn chuyển khoản.': 'Moderate B2C and B2B VIP plan requests via bank transfer invoices.',
    'Yêu cầu đang chờ kiểm duyệt': 'Pending Requests',
    'Làm mới': 'Refresh',
    'Tài khoản': 'Account',
    'Gói Đăng Ký': 'Subscription Plan',
    'Ngày yêu cầu': 'Request Date',
    'Minh chứng chuyển khoản': 'Transfer Proof',
    'Hành động': 'Action',
    'Đang tải dữ liệu thực từ máy chủ...': 'Loading live data from server...',
    'Sạch bóng hàng chờ! Không có yêu cầu nâng cấp nào đang chờ xử lý.': 'Queue is empty! No pending upgrade requests.',
    'Xem hóa đơn chuyển khoản': 'View transfer invoice',
    'Phê duyệt đưa lên Gallery': 'Approve to Gallery',
    'Phê duyệt': 'Approve',
    'Từ chối': 'Reject',
    'Quản lý Thành viên & Salon': 'Manage Members & Salons',
    'Danh sách thông tin, phân cấp tài khoản B2C và các đối tác tiệm nail/thợ nail B2B.': 'Information list, B2C account tiers, and B2B nail salon/technician partners.',
    'Tìm theo tên, email...': 'Search by name, email...',
    'Tên Thành viên': 'Member Name',
    'Email': 'Email',
    'Loại tài khoản': 'Account Type',
    'Trạng thái': 'Status',
    'Ngày gia nhập': 'Join Date',
    'Đang tải danh sách thành viên thực tế từ Database...': 'Loading member list from Database...',
    'Không tìm thấy thành viên nào.': 'No members found.',
    'Vô thời hạn': 'Lifetime',
    'Sửa': 'Edit',
    'Khóa tài khoản': 'Lock account',
    'Kích hoạt tài khoản': 'Activate account',
    'Quản lý Tài nguyên Configurator 3D': 'Manage 3D Configurator Assets',
    'Quản lý các assets 3D bao gồm dáng móng, các file màu sơn \\(textures\\) và charm đính móng được tải nạp thời gian thực.': 'Manage 3D assets including nail shapes, paint colors (textures) and nail charms loaded in real-time.',
    'Thư viện Assets 3D hệ thống': 'System 3D Assets Library',
    'Thêm mới Asset': 'Add New Asset',
    'Loại:': 'Type:',
    'File nguồn:': 'Source File:',
    'Số lượt áp dụng thiết kế:': 'Design applications:',
    'lượt': 'times',
    'Kiểm duyệt Thư viện thiết kế Cộng đồng \\(Gallery\\)': 'Community Gallery Moderation',
    'Xem xét, phê duyệt hoặc ẩn các thiết kế 3D móng mà người dùng chia sẻ lên Gallery cộng đồng, xử lý báo cáo vi phạm tiêu chuẩn cộng đồng.': 'Review, approve or hide 3D nail designs shared by users to the Community Gallery, handle community standard violation reports.',
    'Danh sách bài chia sẻ kiểm duyệt': 'List of shared posts for moderation',
    'Thiết kế bởi:': 'Designed by:',
    'Bị báo cáo:': 'Reported:',
    'Duyệt': 'Approve',
    'Xóa/Ẩn bài đăng': 'Delete/Hide post',
    'Ẩn': 'Hide',
    'Giao dịch thành công': 'Transaction Successful',
    'Người gửi:': 'Sender:',
    'Người nhận:': 'Receiver:',
    'Nội dung chuyển khoản:': 'Transfer Description:',
    'Mã giao dịch \\(FT\\):': 'Transaction Code (FT):',
    'Số tiền:': 'Amount:',
    'Xác nhận đã khớp tiền': 'Confirm payment matched',
    'Chỉnh sửa Thông tin': 'Edit Information',
    'Họ \\(First Name\\)': 'First Name',
    'Tên \\(Last Name\\)': 'Last Name',
    'Vai trò \\(Role\\)': 'Role',
    'Khách hàng \\(USER\\)': 'Customer (USER)',
    'Tiệm Nail \\(SALON\\)': 'Nail Salon (SALON)',
    'Quản trị viên \\(ADMIN\\)': 'Admin (ADMIN)',
    'Lưu Thay Đổi': 'Save Changes',
    'Lỗi khi tải yêu cầu nâng cấp gói:': 'Error loading upgrade requests:',
    'Lỗi khi tải thành viên từ DB:': 'Error loading members from DB:',
    'Bạn chắc chắn muốn duyệt yêu cầu này\\?': 'Are you sure you want to approve this request?',
    'Bạn chắc chắn muốn từ chối yêu cầu này\\?': 'Are you sure you want to reject this request?',
    'Đã duyệt thành công yêu cầu!': 'Request approved successfully!',
    'Đã từ chối thành công yêu cầu!': 'Request rejected successfully!',
    'Có lỗi xảy ra từ máy chủ!': 'Server error occurred!',
    'Không thể kết nối đến máy chủ backend!': 'Cannot connect to backend server!',
    'Không thể kết nối đến máy chủ': 'Cannot connect to server',
    'Có lỗi khi cập nhật trạng thái': 'Error updating status',
    'Cập nhật thông tin thành viên thành công!': 'Member info updated successfully!',
    'Cập nhật thất bại!': 'Update failed!',
    'Lỗi kết nối máy chủ!': 'Server connection error!',
    'Thêm mới mô hình 3D \\(\\.gltf\\) / Texture \\(\\.png\\) cho configurator': 'Add new 3D model (.gltf) / Texture (.png) for configurator',
    'Cập nhật file 3D cho:': 'Update 3D file for:',
    'Dáng móng Almond \\(Hạnh Nhân\\)': 'Almond Nail Shape',
    'Dáng móng Coffin \\(Hòm Bia\\)': 'Coffin Nail Shape',
    'Dáng móng Stiletto \\(Nhọn\\)': 'Stiletto Nail Shape',
    'Sơn bóng Metallic Hồng': 'Pink Metallic Polish',
    'Sơn lì Matte Đen': 'Black Matte Polish',
    'Charm Hoa Đào 3D': '3D Sakura Blossom Charm',
    'Đá Đính Vương Miện Gold': 'Gold Crown Gem',
    'Đã ghi nhận thanh toán thành công!': 'Payment recorded successfully!',
    "actionVi = action === 'approve' \\? 'duyệt' : 'từ chối'": "actionVi = action === 'approve' ? 'approve' : 'reject'",
    'Bạn chắc chắn muốn \\$\\{actionVi\\} yêu cầu này\\?': 'Are you sure you want to ${actionVi} this request?',
    'Đã \\$\\{actionVi\\} thành công yêu cầu!': 'Successfully ${actionVi} request!',
    'Tìm theo tên, email': 'Search by name, email',
    'Tên thành viên': 'Member Name'
};

for (const [pattern, replacement] of Object.entries(replacements)) {
    content = content.replace(new RegExp(pattern, 'g'), replacement);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log('Done translating AdminDashboard.jsx');
